export const STANDARD_LEDGER_ACCOUNTS = [
  // Cash/Bank/Receivables/Payables
  { code: "1000", name: "Cash / Bank", type: "ASSET" },
  { code: "1010", name: "Bank - Retail Operations", type: "ASSET" },
  { code: "1020", name: "Bank - VAT Collections", type: "ASSET" },
  { code: "1100", name: "Payment Gateway Receivables", type: "ASSET" },
  { code: "1110", name: "Accounts Receivable (AR)", type: "ASSET" },
  { code: "1210", name: "Inventory - Wholesale", type: "ASSET" },
  { code: "1300", name: "Prepaid Import Costs", type: "ASSET" },
  { code: "1400", name: "Fleet & Delivery Assets", type: "ASSET" },
  { code: "1500", name: "Investment in Subsidiaries", type: "ASSET" },
  { code: "1600", name: "Intangible Assets - Brand & Software", type: "ASSET" },
  { code: "2000", name: "Accounts Payable (AP)", type: "LIABILITY" },
  { code: "2200", name: "PAYE & Payroll Liabilities", type: "LIABILITY" },
  { code: "2400", name: "Accrued Import Costs", type: "LIABILITY" },
  { code: "2500", name: "Management Fee Payable - Group", type: "LIABILITY" },
  { code: "2600", name: "Logistics Charges Payable", type: "LIABILITY" },
  { code: "3000", name: "Share Capital", type: "EQUITY" },
  { code: "3100", name: "Retained Earnings", type: "EQUITY" },
  { code: "3200", name: "Current Year Profit", type: "EQUITY" },

  // VAT
  { code: "2100", name: "VAT Output Payable", type: "LIABILITY" },
  { code: "2110", name: "VAT Input Recoverable", type: "ASSET" },

  // WHT
  { code: "2300", name: "Withholding Tax (WHT) Payable", type: "LIABILITY" },
  { code: "2310", name: "Withholding Tax (WHT) Receivable/Credit", type: "ASSET" },

  // Revenue
  { code: "4000", name: "Sales Revenue (Reporting Only)", type: "REVENUE" },
  { code: "4010", name: "Wholesale Sales - VAT Inclusive", type: "REVENUE" },
  { code: "4020", name: "Sales Discounts & Rebates", type: "REVENUE" },
  { code: "4100", name: "Sales Returns", type: "REVENUE" },
  { code: "4200", name: "Online Sales Revenue", type: "REVENUE" },
  { code: "4210", name: "Platform Service Fees", type: "REVENUE" },
  { code: "REV_SALES", name: "Sales Revenue", type: "REVENUE" },
  { code: "4300", name: "Logistics Service Revenue", type: "REVENUE" },
  { code: "4500", name: "Management/Shared Services Revenue", type: "REVENUE" },
  { code: "4510", name: "Brand & IP Licensing Income", type: "REVENUE" },
  { code: "4600", name: "IP / Royalty Revenue", type: "REVENUE" },
  { code: "IC_REV", name: "Intercompany Revenue", type: "REVENUE" },

  // Inventory/COGS/Expenses
  { code: "1200", name: "Inventory", type: "ASSET" },
  { code: "5000", name: "Cost of Goods Sold (COGS)", type: "COGS" },
  { code: "5100", name: "Inventory Shrinkage", type: "COGS" },
  { code: "5200", name: "Import Duties & Clearing Costs", type: "COGS" },
  { code: "5300", name: "FX Loss / Gain", type: "COGS" },
  { code: "6000", name: "Operating Expenses (General)", type: "EXPENSE" },
  { code: "6010", name: "Procurement Salaries", type: "EXPENSE" },
  { code: "6020", name: "Utilities", type: "EXPENSE" },
  { code: "6030", name: "Insurance", type: "EXPENSE" },
  { code: "6040", name: "Local Delivery Expense", type: "EXPENSE" },
  { code: "6050", name: "Repairs & Maintenance", type: "EXPENSE" },
  { code: "6060", name: "Marketing", type: "EXPENSE" },
  { code: "6100", name: "Management Fees Expense", type: "EXPENSE" },
  { code: "6110", name: "Sales Commissions", type: "EXPENSE" },
  { code: "6120", name: "Store Staff Salaries", type: "EXPENSE" },
  { code: "6130", name: "POS Charges", type: "EXPENSE" },
  { code: "6200", name: "Logistics Expense", type: "EXPENSE" },
  { code: "6210", name: "Hosting & Cloud Services", type: "EXPENSE" },
  { code: "6220", name: "Digital Marketing", type: "EXPENSE" },
  { code: "6300", name: "Software / Platform Fees", type: "EXPENSE" },
  { code: "6310", name: "Vehicle Maintenance", type: "EXPENSE" },
  { code: "6320", name: "Insurance", type: "EXPENSE" },
  { code: "6500", name: "Directors Fees", type: "EXPENSE" },
  { code: "6510", name: "Group Strategy & Consulting", type: "EXPENSE" },
  { code: "6520", name: "Group Accounting & Audit", type: "EXPENSE" },
  { code: "6530", name: "Legal & Compliance", type: "EXPENSE" },
  { code: "6540", name: "IT Systems & Software", type: "EXPENSE" },
  { code: "6550", name: "Amortisation - Intangibles", type: "EXPENSE" },
  { code: "IC_EXP", name: "Intercompany Expense", type: "EXPENSE" },

  // Tax Provisions
  { code: "TAX_CIT_EXP", name: "Income Tax Expense", type: "EXPENSE" },
  { code: "TAX_CIT_PAY", name: "Income Tax Payable", type: "LIABILITY" },
  { code: "TAX_EDU_EXP", name: "Education Tax Expense", type: "EXPENSE" },
  { code: "TAX_EDU_PAY", name: "Education Tax Payable", type: "LIABILITY" },
] as const;
